### ISSUE TITLE
Lint throws errors

### ISSUE THREAD

**Issue by drgrigg** [oswallt/l-m-montgomery_anne-of-avonlea#1]
When I run lint I'm seeing quite a few errors thrown. Just as a check, if you're not seeing these, I'm running se version 2.4.2.

The first error I see in lint, "c-015" relates to how you've treated the children's letters in Chapter 11. Lint is expecting that a paragraph following a salutation should have no indent and be styled that way in CSS.

Certainly it was worth giving special formatting to Ned Clay's letter, but looking at the page scans, I don't think the letters which _follow_ Ned's letter need to be treated specially, just formatted the way shown in our manual, other than the odd capitalisation of Edward Blake Clay's signature.

You might need to use an se-lint-ingore.xml file to stop lint complaining about Ned Clay's letter, however. See https://standardebooks.org/manual/1.7.0/single-page#2.3 .

The second lint error "t-029" just looks like it's picking up spurious periods which probably would be commas in the page scans.

The next error "t-030" is thrown by Ned's letter, as we don't expect an abbreviation to be spaced like that. This also would be a good candidate for se-lint-ignore.xml.

The next, "t-042" is because of a misplaced comma in dialog in Chapter 17, `I’m too much inclined that, way” agreed Anne` should be `I’m too much inclined that way,” agreed Anne`.

The last lint error I see "c-008" relates to the CSS class you've created to deal with a signature following a postscript at the very end of Chapter 11. I would just put that in a new paragraph and give it the signature epub:type.

Can you have a look at these?

**Comment by oswallt** [comment]
I have updated the tools and I'm seeing all of that.  I'll get that fixed up.

**Comment by drgrigg** [comment]
Please let me know when you’ve pushed those changes and I’ll continue the review.

**Comment by oswallt** [comment]
OK, I've taken care of the lint errors.
